In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("sohaibdevv/ai-and-student-life-2026-the-new-normal")
print(path)

c:\stuff\Code\Python\Machine-Learning\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

C:\Users\user\.cache\kagglehub\datasets\sohaibdevv\ai-and-student-life-2026-the-new-normal\versions\1

In [2]:
import os
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error as MSE, mean_absolute_error as MAE, accuracy_score 
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.preprocessing import MultiLabelBinarizer, StandardScaler
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, BaggingRegressor

In [3]:
data = pd.read_csv(os.path.join(path, os.listdir(path)[0]))
data.head()

,Student_ID,Age,Major,Primary_AI_Tool,Task_Frequency_Daily,Main_Usage_Case,GPA_Baseline,GPA_Post_AI,Time_Saved_Hours_Weekly,AI_Ethics_Concern,Career_Confidence_Score
0,STU-6019,23,Software Engineering,Gemini Pro,1,Code Debugging,2.62,2.62,9,Medium,3
1,STU-6962,22,Modern History,GitHub Copilot,3,Essay Drafting,3.99,4.00,7,Medium,4
2,STU-2338,18,Data Science,Perplexity,2,Literature Review,2.57,2.57,15,High,7
3,STU-1380,19,Biology,Claude 3.5,5,Essay Drafting,2.67,2.87,12,Low,5
4,STU-1837,19,Biology,ChatGPT-4o,10,Code Debugging,3.65,3.85,5,High,9

# Data cleanup and preprocessing

In [13]:
dropped_data = data.drop(columns="Student_ID")
data["AI_Ethics_Concern"].unique()
data.isna().sum()

Student_ID                 0
Age                        0
Major                      0
Primary_AI_Tool            0
Task_Frequency_Daily       0
Main_Usage_Case            0
GPA_Baseline               0
GPA_Post_AI                0
Time_Saved_Hours_Weekly    0
AI_Ethics_Concern          0
Career_Confidence_Score    0
dtype: int64

In [12]:
AI_ethics_order = {"Low": 1, "Medium" : 2, "High": 3}
dropped_data["AI_Ethics_level"] = dropped_data["AI_Ethics_Concern"].map(AI_ethics_order)
leveled_data = dropped_data.drop(columns="AI_Ethics_Concern")

dummified = pd.get_dummies(leveled_data, drop_first=True)
dummified.head()

,Age,Task_Frequency_Daily,GPA_Baseline,GPA_Post_AI,Time_Saved_Hours_Weekly,Career_Confidence_Score,AI_Ethics_level,Major_Business Administration,Major_Data Science,Major_Fine Arts,Major_Modern History,Major_Software Engineering,Primary_AI_Tool_Claude 3.5,Primary_AI_Tool_Gemini Pro,Primary_AI_Tool_GitHub Copilot,Primary_AI_Tool_Perplexity,Main_Usage_Case_Code Debugging,Main_Usage_Case_Essay Drafting,Main_Usage_Case_Exam Prep,Main_Usage_Case_Literature Review
0,23,1,2.62,2.62,9,3,2,False,False,False,False,True,False,True,False,False,True,False,False,False
1,22,3,3.99,4.00,7,4,2,False,False,False,True,False,False,False,True,False,False,True,False,False
2,18,2,2.57,2.57,15,7,3,False,True,False,False,False,False,False,False,True,False,False,False,True
3,19,5,2.67,2.87,12,5,1,False,False,False,False,False,True,False,False,False,False,True,False,False
4,19,10,3.65,3.85,5,9,3,False,False,False,False,False,False,False,False,False,True,False,False,False